version: '3'
services:
  api:
    networks:
      - lambda-local
  db:
    ports:
      - 3306:3306
    networks:
      - lambda-local
  dynamodb:
    ports:
      - 3307:8000
    networks:
      - lambda-local
networks:
  lambda-local:
    external: true
